---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: sonarr-deployment
   labels:
     app: sonarr
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: sonarr
   template:
     metadata:
       labels:
         app: sonarr

     spec:
      containers:
         - name: sonarr
           image: linuxserver/sonarr
           ports:
             - containerPort: 8989
           volumeMounts:
             - mountPath: /config
               name: sonarr-config
             - mountPath: /tv
               name: sonarr-tv
             - mountPath: /downloads
               name: nzbget-downloads
      volumes:
        - name: sonarr-config
          hostPath:
            path: /mnt/NAS1NFS/sonarr-config
        - name: sonarr-tv
          hostPath:
            path: /mnt/NAS1NFS/TV
        - name: nzbget-downloads
          hostPath:
            path: /mnt/NAS1NFS/Downloads
---
kind: Service
apiVersion: v1
metadata:
  name: sonarr-service
spec:
  selector:
    app: sonarr
  ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
    nodePort: 32766
  type: NodePort
